name: learn-github-actions
run-name: Full forward migrations only
on: [pull_request]
jobs:
  check-incremental:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.pull_request.head.sha }}
          path: "head"
      - run: ls head/migrations
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.pull_request.base.sha }}
          path: "base"
          run: ls base/migrations
